/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajarireport;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MIKO
 */
public class FormContoh extends javax.swing.JFrame {

    /**
     * Creates new form FormContoh
     */
    public FormContoh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Button Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Belajar Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            //JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportSembako.jrxml"),null, Koneksi.getConnection());
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportSembako.jasper"),null, Koneksi.getConnection());
            //JasperViewer.viewReport(jp);
            JasperViewer jViewer = new JasperViewer(jp,false);
            jViewer.setVisible(true);
            //new Koneksi().getConnection();
            //JasperExportManager.exportReportToPdfFile(jp, "C:/report.pdf");
            //JasperViewer jv = new JasperViewer(jp);
            //jv.show();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan","Cetak Laporan",JOptionPane.ERROR_MESSAGE);
            //System.out.println(e.getMessage());
            System.out.println(e.toString());
        }
            
        /*try{
            JasperReport masterReport = null;
            try{
		masterReport = (JasperReport) JRLoader.loadObject(getClass().getResource("reportSembako.jasper"));
            }catch(Exception e){
		System.out.println("error lagi");
            }
            JasperPrint jasperPrint = JasperFillManager.fillReport(masterReport,null,Koneksi.getConnection());
            JasperViewer jViewer = new JasperViewer(jasperPrint, false);
            jViewer.setVisible(true);
        }catch(JRException e){
            //JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan","Cetak Laporan",JOptionPane.ERROR_MESSAGE);
            System.out.println(e.toString());
        }*/
        
        /*try{
            String namefile = "src/belajarireport/reportSembako.jasper";
            File report = new File(namefile);
            JasperReport jreprt = (JasperReport)JRLoader.loadObject(report.getPath());
            JasperPrint jprintt = JasperFillManager.fillReport(jreprt,null,Koneksi.getConnection());
            JasperViewer.viewReport(jprintt,false);
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan","Cetak Laporan",JOptionPane.ERROR_MESSAGE);
            System.out.println(e.toString());
        }*/
        
        /*try{
            InputStream in = new FileInputStream(new File("C:\\Users\\MIKO\\Documents\\NetBeansProjects\\BelajarIreport\\src\\belajarireport\\reportSembako.jrxml"));
            JasperDesign jd = JRXmlLoader.load(in);
            String sql = "select *from tb_sembako";
            JRDesignQuery newQuery  = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint j = JasperFillManager.fillReport(jr,null,Koneksi.getConnection());
            JasperViewer.viewReport(j, false);
            OutputStream os = new FileOutputStream(new File("E:\\Reports"));
            JasperExportManager.exportReportToPdfStream(j,os);
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan","Cetak Laporan",JOptionPane.ERROR_MESSAGE);
            System.out.println(e.toString());
        }*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormContoh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
